# Configuration file for Handshake automation
# This file contains all configuration settings for the job application bot
# Auto-generated by the application - do not edit manually unless you know what you're doing

# Whether the configuration is valid and ready to use
VALID = True

# Search URL with filters (will be sanitized)
URL = 'https://app.joinhandshake.com/job-search/10382339?employmentTypes=1&jobType=9&pay%5BsalaryType%5D=1&majors=35471&qualifications=majors&jobRoleGroups=64&workAuthorization=openToUSVisaSponsorship&workAuthorization=openToOptionalPracticalTraining&per_'

# Document IDs for application
# Data Analyst Resume
# https://app.joinhandshake.com/job-search/10410522?pay%5BsalaryType%5D=1&majors=35471&qualifications=majors&jobRoleGroups=72&jobRoleGroups=67&jobRoleGroups=36&jobRoleGroups=73&jobRoleGroups=392&jobRoleGroups=55&jobRoleGroups=65&jobRoleGroups=56&workAuthorization=openToUSVisaSponsorship&workAuthorization=openToOptionalPracticalTraining&per_page=50&employmentTypes=1&jobType=9&sort=posted_date_desc&page=1
# RESUME = 61560036

# AI/ML Resume
# https://app.joinhandshake.com/job-search/10399838?query=AI&pay%5BsalaryType%5D=1&majors=35471&qualifications=majors&workAuthorization=openToUSVisaSponsorship&workAuthorization=openToOptionalPracticalTraining&per_page=50&employmentTypes=1&jobType=9&sort=posted_date_desc&page=1
# https://app.joinhandshake.com/job-search/10410517?query=machine+learning&pay%5BsalaryType%5D=1&majors=35471&qualifications=majors&workAuthorization=openToUSVisaSponsorship&workAuthorization=openToOptionalPracticalTraining&per_page=50&employmentTypes=1&jobType=9&sort=posted_date_desc&page=1
# RESUME = 61560072

# SDE Resume
# https://app.joinhandshake.com/job-search/10390237?pay%5BsalaryType%5D=1&majors=35471&qualifications=majors&jobRoleGroups=64&jobRoleGroups=66&jobRoleGroups=65&jobRoleGroups=487&jobRoleGroups=57&jobRoleGroups=8&jobRoleGroups=397&jobRoleGroups=396&jobRoleGroups=60&jobRoleGroups=59&jobRoleGroups=58&jobRoleGroups=63&jobRoleGroups=55&workAuthorization=openToUSVisaSponsorship&workAuthorization=openToOptionalPracticalTraining&per_page=50&employmentTypes=1&jobType=9&sort=posted_date_desc&page=1
RESUME = 61560055

COVER = 61560812
TRANSCRIPT = 52936640
OTHER = None

# Last run date (ISO format)
DATE = '2025-10-15T01:11:17.579534'

# Job keywords to look for (not currently used in code but from template)
JOB_KEYWORDS = []

# Keywords to skip jobs with (not currently used in code but from template)
SKIP_KEYWORDS = []

# Session cookies - REQUIRED for authentication
COOKIES = {   '__cf_bm': '31MRBqP3Siwi5BG_Xbrds3eFYqsHvrIoJyptrzQq_E4-1760489501-1.0.1.1-qpvVC1P9HKp.qgs1RpOjLMxp51ka81o8CJkCRjh10vKJUZd7_QAkOSyVz6EB7m8yMFVm91o1mx7XAhJPeGINTSSHDPXljDeBVVnqkN9hJwQ',
    '_cfuvid': 'gJCjkCDbFLR4AjGnD1UYNTuuFs5w.eMdrOM49jQaNTY-1760489500984-0.0.1.1-604800000',
    '_dd_s': 'aid=db2ad0bc-1427-4919-9e2b-34536b55f7f9&rum=0&expire=1760371279587&logs=1&id=1fb55213-b9e0-4080-b5ce-dc03f5565b58&created=1760367918705',
    '_ga': 'GA1.1.1280275205.1760324338',
    '_ga_4M16ZMP2G5': 'GS2.1.s1760367919$o2$g1$t1760370313$j60$l0$h0',
    '_trajectory_session': 'U%2BCAXAeKhWUL3w1xSgmP2c07PZnyWKwAG0kLl7LyDBTLCoJcbieJDuSEK1bpDh4MYoYl%2BvFerlmta3cNv%2FjBCdmi%2FNDmi%2Fh1lca%2FB%2FZz7xrmz1GPV4%2FmPAph88mThH2%2BnOj6Ds59Cr9Di8YvX5psP8Wy4uIsz9RmcgKDwJIE%2FRR%2Fb5hxlZQNu3Xu4LT0S0ED%2FMfRJr6nCnn3j%2B5axEZoc%2BXYrzP8FUnT47%2B053tDVZWE0pQ%3D--HBDqH7jiy9jA3AfD--kRn2L%2Bh0vOnvAe%2FnFxYaDw%3D%3D',
    'ajs_anonymous_id': 'c049d4b8-111a-4a1b-945b-e461939cd76e',
    'ajs_user_id': '59906404',
    'hss-global': 'eyJhbGciOiJkaXIiLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwidHlwIjoiSldUIn0..YEtxe6zBuTmJ-tnZbGcQaw.vBcCEmOKWc1uiLyAnvlV6jv1bmTp3MpMgfqXYpEqaubW3yPHbmwhqAxtkLkRnn4WQc2ZuXoz-q6CZk6WKicadx4S6l1jXY0tvphp4VYUwWtcKWCmTAyQ9GPSvfjPjxo_IRrl2ziI_bXDE3RNpwA-p5UMF4iIsOOKwSpS4M2BnI1dBpRjnaFClmJ6mtscnFYUd6EJ50o2puvLKVaQWZaYMnBEyi5UNmbr3tKy4JpKvoukUeZO8r7ni4iFTswuVLo8Om3qijEwN_C8yIj9d66e8j1VP4sH_vIduI9ILgyJCKogHcSfH88aM72WNkr0HE7moqnRPlcgfvj3KRJBCeJSwHn5QZS5MUkqNl0hTruVa_2L6L-lMD1HtYYxpjcb4NJT.GkgjZToSveoGq0ez4GlRTJUmeF0VFAqeJYDAE5c1ibM',
    'production_59906404_follow-tooltip': '%22true%22',
    'production_59906404_incident-warning-banner-show': '%5B%5D',
    'production_current_user': '59906404',
    'production_js_on': 'true',
    'production_submitted_email_address': 'eyJfcmFpbHMiOnsibWVzc2FnZSI6IkluQnRZV2hsYzJoM1lYSmhia0JpYVc1bmFHRnRkRzl1TG1Wa2RTST0iLCJleHAiOiIyMDQ1LTEwLTEzVDAzOjA3OjA3Ljg4M1oiLCJwdXIiOm51bGx9fQ%3D%3D--b120f138174057038558600a9db71c84154d1ebd',
    'request_method': 'POST'}
